
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "email1",
  "password": "password1"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "login": "user4",
  "email": "email4",
  "password": "password4"
}

###
POST http://localhost:3000/api/post
Content-Type: application/json

{
  "text": "First user post"
}

###
POST http://localhost:3000/api/message
Content-Type: application/json

{
  "sender_id": "6389ee473a59ad984960e97b",
  "dialog_id": "6389eece3a59ad984960e981",
  "text": "Hi!"
}

###
POST http://localhost:3000/api/dialog
Content-Type: application/json

{
  "members_id": [
    "6389ee473a59ad984960e97b",
    "6389ea976372580be6b8f066"
  ]
}

###

GET http://localhost:3000/api/user
authorization: 6389eb695fdc5cb837575667

###

GET http://localhost:3000/api/message

###

GET http://localhost:3000/api/post

###

GET http://localhost:3000/api/dialog
authorization: 6389eb695fdc5cb837575667

###

PUT http://localhost:3000/api/post/like/638cb4fd2fcb67b4aa2bfdfb
authorization: 638cb4f92fcb67b4aa2bfdf4

###

DELETE http://localhost:3000/api/post/638cb2d856e43ebb3c584cf0
