
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "email1",
  "password": "password1"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "login": "user4",
  "email": "email4",
  "password": "password4"
}

###
POST http://localhost:3000/api/post
Content-Type: application/json

{
  "text": "First user post"
}

###

POST http://localhost:3000/api/message
Content-Type: application/json
authorization: 639ec7225edf70d6e3d1057b

{
  "dialog_id": "639ee9dbdae6114ff58fd445",
  "text": "How are you?"
}

###

GET http://localhost:3000/api/message
authorization: 638cb4f92fcb67b4aa2bfdf4

###
POST http://localhost:3000/api/dialog
Content-Type: application/json
authorization: 638d0f848c5159385112a242

{
  "members_id": [
    "6390eb9941f9341b63588667"
  ]
}

###

GET http://localhost:3000/api/user
authorization: 6389eb695fdc5cb837575667

###

GET http://localhost:3000/api/message/638dda7a0549a7286372f04e
authorization: 638cb4f92fcb67b4aa2bfdf4

###

PUT http://localhost:3000/api/message/check/63ab1174fe9cd0d033c2dc5e
authorization: 63a15a6e5b1d3686284d2365

###

GET http://localhost:3000/api/post/

###

GET http://localhost:3000/api/dialog
authorization: 638cb4f92fcb67b4aa2bfdf4

###

PUT http://localhost:3000/api/post/like/638dce155d24a175b1b9b2b3
authorization: 638cb4f92fcb67b4aa2bfdf4

###

DELETE http://localhost:3000/api/post/638cfec6108c2f607b60b456
authorization: 638cb4f92fcb67b4aa2bfdf4

###

POST https://social-network-server-rho.vercel.app/api/dialog
Content-Type: application/json
authorization: 6390eb9941f9341b63588667

{
  "members_id": [
    "638d10e8688ad92faf870be0"
  ]
}

###

POST https://social-network-server-rho.vercel.app/api/message
Content-Type: application/json
authorization: 638d0f848c5159385112a242

{
  "dialog_id": "6394a26c785b9b2764d5ca47",
  "text": "How are you?"
}

###

PUT http://localhost:3000/api/user/subscribe/user2
authorization: 638cb4f92fcb67b4aa2bfdf4

###

POST http://localhost:3000/api/user/update
Content-Type: application/json
authorization: 638cb4f92fcb67b4aa2bfdf4

{
  "login": "user1",
  "email": "user1@gmail.com",
  "password": "password1"
}

###

GET http://localhost:3000/api/image/user2_avatar.png